#pragma config(Sensor, S1,     SensorOne,      sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)

	if (SensorValue(SensorOne) < 10) {
		motor[motorA] = 50;
		motor[motorD] = 50;
		}else {
		motor[motorA] = 30;
		motor[motorD] = -30;
	}

}
